# Generated by Django 4.1.5 on 2023-02-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('emid', models.CharField(max_length=20)),
            ],
        ),
    ]
